version: "latest"
image: aliangbaby/home-assistant-matter-hub
slug: hamh-beta
name: Home-Assistant-Matter-Hub (Aliang)
description: Beta Releases of Home Assistant Matter Hub
url: https://github.com/Aliang-code/home-assistant-matter-hub
panel_icon: mdi:hub
panel_title: Matter Hub (Aliang)
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
